SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
SET ANSI_WARNINGS ON;
SET ANSI_PADDING ON;
SET CONCAT_NULL_YIELDS_NULL ON;
SET NUMERIC_ROUNDABORT OFF;

IF COL_LENGTH('dbo.tbl_Venta', 'todoOk') IS NULL
BEGIN
    ALTER TABLE dbo.tbl_Venta
    ADD todoOk BIT NOT NULL DEFAULT(0);
END;
